#!/usr/bin/env python3

import sys
import os

path = ""

try: 
    path = sys.argv[1]
except:
    print("Use path to tfvars file as an argument")
    exit(2)

if os.path.isfile(path):
    print("File found")
    new_content = []
    hcl_file_name = path.replace('.tfvars','.hcl')
    with open(path) as f:
        lines = f.read().splitlines()
        clear_lines = list(filter(None, lines))
        new_content.extend(clear_lines)
    
    hcl_content = "locals {\n"
    for line in new_content:
        line = "\t" + line + "\n"
        hcl_content = hcl_content + line

    hcl_content = hcl_content + "}\n"
    print(f'Writing updates to {hcl_file_name}')
    output = open(hcl_file_name, 'w')
    output.writelines(hcl_content)
    output.close()

else:
    print("File not found")
    exit(2)

